# Generated by Django 5.2.14 on 2026-05-22 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_profile_tuteur"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="role",
            field=models.CharField(
                choices=[
                    ("etudiant", "Etudiant"),
                    ("tuteur", "Tuteur"),
                    ("enseignant", "Enseignant"),
                ],
                max_length=20,
            ),
        ),
    ]
