# Generated by Django 5.2.14 on 2026-05-22 18:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_categorieevaluation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cataloguemodule",
            name="coefficient",
            field=models.PositiveIntegerField(
                validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
    ]
