# Generated by Django 5.2.14 on 2026-05-24 12:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_alter_cataloguemodule_coefficient"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categorieevaluation",
            name="poids",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AlterUniqueTogether(
            name="categorieevaluation",
            unique_together={("module", "nom")},
        ),
    ]
