# Generated by Django 5.2.14 on 2026-05-24 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_alter_categorieevaluation_poids_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="categorieevaluation",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="categorieevaluation",
            name="poids",
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
