# Generated by Django 5.2.14 on 2026-05-23 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enrollment", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="inscription",
            name="annee_academique",
            field=models.CharField(default="2025/2026", max_length=20),
            preserve_default=False,
        ),
    ]
