# Generated by Django 5.2.14 on 2026-05-20 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_categorieevaluation"),
        ("enrollment", "0002_modulechoisi"),
    ]

    operations = [
        migrations.CreateModel(
            name="Note",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("valeur", models.FloatField()),
                ("date_saisie", models.DateTimeField(auto_now_add=True)),
                (
                    "categorie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.categorieevaluation",
                    ),
                ),
                (
                    "module_choisi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="enrollment.modulechoisi",
                    ),
                ),
            ],
            options={
                "unique_together": {("module_choisi", "categorie")},
            },
        ),
    ]
