# Generated by Django 5.2.14 on 2026-05-24 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_alter_cataloguemodule_coefficient"),
        ("enrollment", "0002_inscription_annee_academique"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="note",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="note",
            name="type_note",
            field=models.CharField(
                choices=[("officielle", "Officielle"), ("estimation", "Estimation")],
                default="officielle",
                max_length=20,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="note",
            unique_together={("module_choisi", "categorie", "type_note")},
        ),
    ]
