# Generated by Django 5.2.14 on 2026-05-24 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("enrollment", "0004_alter_inscription_user_alter_note_valeur_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="note",
            options={"ordering": ["date_saisie"]},
        ),
        migrations.AlterUniqueTogether(
            name="note",
            unique_together=set(),
        ),
    ]
