# Generated by Django 5.2.14 on 2026-05-23 14:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enrollment", "0006_remarqueenseignant_suivituteur_delete_remarque"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="suivituteur",
            name="etudiant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="suivis_tuteur",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="suivituteur",
            name="tuteur",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="suivis_encadres",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
